RPG_Buddy/RPG_Buddy/Models/CharacterCard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RPG_Buddy.Models
{
    public class CharacterCard
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual List<CharacterCardFormValue> CharacterCardFormValues { get; set; }
        
        public int Rating { get; set; }
        public virtual List<CharacterVote> Votes { get; set; }

        public CharacterCard()
        {

            Votes = new List<CharacterVote>();
        }

    }
}

RPG_Buddy/RPG_Buddy/Models/CharacterCardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RPG_Buddy.Models
{
    public class CharacterCardViewModel
    {
        public string ImieNazwisko { get; set; }
        public string CharacterTemplate { get; set; }
        public List<string> CharacterTemplateNames { get; set; }


    }
}

RPG_Buddy/RPG_Buddy/Controllers/CharacterCardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RPG_Buddy.Models;
using System.Diagnostics;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;

namespace RPG_Buddy
{
    public class CharacterCardController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: CharacterCard
        public ActionResult Index()
        {
            return View(db.CharacterCards.ToList());
        }

        // GET: CharacterCard/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CharacterCard characterCard = db.CharacterCards.Find(id);
            if (characterCard == null)
            {
                return HttpNotFound();
            }
            return View(characterCard);
        }

        // GET: CharacterCard/Create
        public ActionResult Create()
        {
            var model = new CharacterCardViewModel();
            model.CharacterTemplateNames = db.CharacterTemplates.Select(x=> x.Name).ToList();
            return View(model);
        }

        // POST: CharacterCard/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(object obj)
        {
            var keys = Request.Form.AllKeys;

            var characterCard = new CharacterCard();
            characterCard.Name = Request.Form[keys[0]];

            var formValues = new List<CharacterCardFormValue>();
           
            for (int i = 1; i < keys.Length; i++)
            {
                formValues.Add(new CharacterCardFormValue
                {
                    Name = keys[i],
                    Value = Request.Form[keys[i]]
                });
            }
            characterCard.CharacterCardFormValues = formValues;
            db.CharacterCards.Add(characterCard);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult GetTemplate(string name)
        {
            var result = db.CharacterTemplates.FirstOrDefault(x => x.Name == name);
            return Json(result);
        }

        // GET: CharacterCard/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                //id = ViewBag.id;
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            CharacterCard characterCard = db.CharacterCards.Find(id);
            CharacterCardViewModel vm = new CharacterCardViewModel();
            if (characterCard == null)
            {
                return HttpNotFound();
            }

            Session["id"] = id;

          
            return View(characterCard);
        }


        public ActionResult Vote(int characterCardId, int rating = 1)
        {

            //ItemCard ic = db.ItemCards.Find(itemId);

            //string userId = User.Identity.GetUserId();

            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            string userId = user.Id;

            if (userId != null)
            {

                CharacterVote characterVote = new CharacterVote(rating, characterCardId, userId);

                // var votes = from v in db.ItemVotes select  
                var votes = db.CharacterVotes.Where(v => v.CharacterVoteId == characterCardId && v.UserId == userId);
                if (votes.Count() == 0)
                {
                    db.CharacterVotes.Add(characterVote);
                    CharacterCard character = db.CharacterCards.Find(characterCardId);
                    character.Votes.Add(characterVote);
                    db.Entry(character).State = EntityState.Modified;
                    db.SaveChanges(); ;

                    //TODO: make sure item has not been rated by this user before
                    ViewBag.rating = rating;
                    ViewBag.querystatus = "OK";
                    return View("Vote");
                }
                else
                {
                    if (votes.Count() == 1) {
                        var oldVote = votes.First();

                        if (oldVote.Value == rating) { return View("VotedAlready"); }

                        oldVote.Value = rating;
                        db.Entry(oldVote).State = EntityState.Modified;
                        db.SaveChanges();
                        ViewBag.rating = rating;
                        ViewBag.querystatus = "OK";
                        return View("Vote");
                    }

                    /*   ViewBag.querystatus = "FAILURE";
                       return View("Vote");*/
                    return View("VotedAlready");
                }

            }
            ViewBag.querystatus = "FAILURE";
            return View("Vote");

        }

        public int getTotalRating(int Id) {

            var votes = db.CharacterVotes.Where(v => v.CharacterCardId == Id).ToList();
            if (votes.Count != 0)
            {
                var sum = votes.Sum(v => v.Value);
                return sum;
            }
            else return 0;
        }

        /*public ActionResult Upvote()
        {
            int votePower = 1;



            List<int> upvotedList;
            int idFromSession = (int)Session["id"];



            if (Session["downvoted"] != null)
            {
                List<int> dList = (List<int>)Session["downvoted"];
                if (dList.Contains(idFromSession))
                {
                    votePower = 2;
                }
            }


            if (Session["upvoted"] != null)
            {
                upvotedList = (List<int>)Session["upvoted"];
                if (upvotedList.Contains(idFromSession))
                {
                    return View("VotedAlready");
                }
                else
                {

                    //ViewBag.id = null;

                    CharacterCard card = db.CharacterCards
              .Where(c => c.Id == idFromSession).FirstOrDefault();

                    //card.Rating += 1;
                    card.Votes += votePower;



                    db.SaveChanges();

                    upvotedList = (List<int>)Session["upvoted"];
                    upvotedList.Add(idFromSession);
                    Session["upvoted"] = upvotedList;

                    //return RedirectToAction("Index", );
                    return View("Upvote");

                }

            }
            else
            {// list is null

                //ViewBag.id = null;
                CharacterCard card = db.CharacterCards
              .Where(c => c.Id == idFromSession).FirstOrDefault();

                //card.Rating += 1;


                card.Votes += votePower;

                db.SaveChanges();

                //upvotedList = (List<int>)Session["upvoted"];
                upvotedList = new List<int>();
                upvotedList.Add(idFromSession);
                Session["upvoted"] = upvotedList;

                //return RedirectToAction("Index", );
                return View("Upvote");
            }
        }



        public ActionResult Downvote()
        {
            int votePower = 1;



            List<int> downvotedList;
            int idFromSession = (int)Session["id"];



            if (Session["upvoted"] != null)
            {
                List<int> dList = (List<int>)Session["upvoted"];
                if (dList.Contains(idFromSession))
                {
                    votePower = 2;
                }
            }


            if (Session["downvoted"] != null)
            {
                downvotedList = (List<int>)Session["downvoted"];
                if (downvotedList.Contains(idFromSession))
                {
                    return View("VotedAlready");
                }
                else
                {

                    //ViewBag.id = null;

                    CharacterCard card = db.CharacterCards
              .Where(c => c.Id == idFromSession).FirstOrDefault();

                    //card.Rating += 1;
                    card.Votes -= votePower;

                    db.SaveChanges();

                    downvotedList = (List<int>)Session["downvoted"];
                    downvotedList.Add(idFromSession);
                    Session["downvoted"] = downvotedList;

                    //return RedirectToAction("Index", );
                    return View("Upvote");

                }

            }
            else
            {// list is null

                //ViewBag.id = null;
                CharacterCard card = db.CharacterCards
              .Where(c => c.Id == idFromSession).FirstOrDefault();

                //card.Rating += 1;


                card.Votes += votePower;

                db.SaveChanges();

                //upvotedList = (List<int>)Session["upvoted"];
                downvotedList = new List<int>();
                downvotedList.Add(idFromSession);
                Session["downvoted"] = downvotedList;

                //return RedirectToAction("Index", );
                return View("Downvote");
            }
        }*/





RPG_Buddy/RPG_Buddy/Views/CharacterCard/Create.cshtml
@model RPG_Buddy.Models.CharacterCardViewModel

@{
    ViewBag.Title = "Create";
}


    <form id="nameForm">
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>CharacterCard</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.DropDownListFor(m => m.CharacterTemplate, new SelectList(Model.CharacterTemplateNames), new { @class = "form-control", id = "dropDown" })
            </div>


            <div class="form-group">
                <button type="button" id="formButton" value="Create" class="btn btn-default">Wybierz</button>
            </div>
        </div>
    </form>

<h2>Create</h2>
<script type="text/javascript">
    $(document).ready(function () {

        var template;

        $("#dropDown").change(function () {
            //alert("Handler for .change() called.");
        });

        $("#formButton").click(function () {
            var selectedOption = $("#dropDown option:selected").text();
            console.log(selectedOption);
            $.ajax({
                method: 'post',
                url: "/CharacterCard/GetTemplate",
                data: { name: selectedOption }
            }).done(function (data) {
                createForm(data, selectedOption);

            });
            
        });

        function createForm(data, selectedOption) {
            console.log("Selected option aklfjsalkdjsakl", selectedOption);
            $("#nameForm").hide();
            // Generate a form
            //var template1 = { "attributes": ["atr1", "atr2"], "constraints": [{ "maxVal": "10" }, { "minVal": "0" }] }
            //var template = { "attributes": ["sila", "sila", "moc"], "constraints": [{ "maxVal": "100" }, { "minVal": "0" }, { "pointsTotal": "50" }, { "maxVal": "5" }, { "minVal": "50" }, { "pointsTotal": "80" }] }
            console.log(data.Schema, null, 2);
            var template = JSON.parse(data.Schema);
            console.log(JSON.stringify(template, null, 2));
            var html = [];
            
            firstName = {
                "name": "username",
                "caption": "Nazwa postaci",
                "type": "text",
                "class": "form-control"
            }
            html.push(firstName);

            for (var j = 0; j < template.attributes.length; j++) {
                var field = {};
                field.name = template.attributes[j];
                field.caption = template.attributes[j];
                field.type = "text";
                field.class = "form-control";
                html.push(field);
            }
            var submit = {
                "type": "submit",
                "value": "Create",
                "class": "btn btn-default"
            }
            html.push(submit);

            var input = $("<input>")
                .attr("type", "hidden")
                .attr("name", "name").val(selectedOption);
            $('#myform').append($(input));

            console.log(JSON.stringify(html, null, 2));

            $("#myform").dform({
                "action": "/CharacterCard/Create",
                "method": "post",
                "html": html
            })

        }
        $(function () {
            // Generate a form
            //var template1 = { "attributes": ["atr1", "atr2"], "constraints": [{ "maxVal": "10" }, { "minVal": "0" }] }
            /*var template = { "attributes": ["sila", "sila", "moc"], "constraints": [{ "maxVal": "100" }, { "minVal": "0" }, { "pointsTotal": "50" }, { "maxVal": "5" }, { "minVal": "50" }, { "pointsTotal": "80" }] }
            console.log(JSON.stringify(template, null, 2));
            var html = [];

            firstName = {
                "name": "username",
                "id": "txt-username",
                "caption": "Username",
                "type": "text",
                "placeholder": "E.g. user@example.com"
            }

            for (var j = 0; j < template.attributes.length; j++) {
                var field = {};
                field.name = template.attributes[j];
                field.caption = template.attributes[j];
                field.type = "text";
                field.class = "form-control"
                //field.max = template.constraints[j].maxVal;
                html.push(field);
            }
            var submit = {
                "type": "submit",
                "value": "Create",
                "class": "btn btn-default"
            }
            html.push(submit);
            

            console.log(JSON.stringify(html, null, 2));



            $("#myform").dform({
                "action": "/CharacterCard/Create",
                "method": "post",
                "html": html

            })*/
        });
    });
	
</script>
<div class="form-horizontal">
    <form id="myform"></form>
</div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

RPG_Buddy/RPG_Buddy/Views/CharacterCard/Delete.cshtml
@model RPG_Buddy.Models.CharacterCard

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>



    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RPG_Buddy/RPG_Buddy/Views/CharacterCard/Details.cshtml
@model RPG_Buddy.Models.CharacterCard

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CharacterCard</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RPG_Buddy/RPG_Buddy/Views/CharacterCard/Downvote.cshtml


<h2>Dodano minusa</h2>



<table class="table table-bordered table-striped">

    
</table>

RPG_Buddy/RPG_Buddy/Views/CharacterCard/Edit.cshtml
@model RPG_Buddy.Models.CharacterCard

@{
    ViewBag.Title = "Edit";
}


<script type="text/javascript" src="rating.js"></script>
<link rel="stylesheet" type="text/css" href="rating.css" />

<h2>Info</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CharacterCard</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @foreach (var formItem in Model.CharacterCardFormValues)
        {
            <div class="form-group">
                @Html.LabelFor(x => formItem.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(x => formItem.Value, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        }









        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
            
    </div>
}
@{string actionUp = "/CharacterCard/Upvote";
    string actionDown = "/CharacterCard/Downvote";

    Session["id"] = Model.Id;
    int characterCardId = Model.Id;
    var action = "CharacterCard/Vote";
}

@using (Html.BeginForm("Vote", "CharacterCard", FormMethod.Post))
{
    @Html.Hidden("characterCardid", Model.Id);
    <!--<input type="hidden" name="characterCardid" value=@characterCardId />-->
    @Html.DropDownList("rating", new SelectList(new[] { 1, 2, 3, 4, 5 }))
    <!-- <select id="selectNumber" name="rating">
        <option>Choose a number</option>
    </select>-->

    <input type="submit" value="Vote" />
}

@{Html.RenderAction("getTotalRating", new { Id = Model.Id });}



<!--
<form id="voteForm" method="post" action=@action >
    <!-- <input id="hideit1" type="text" class="rating rating10" />
       
    <select id="selectNumber" name="rating">
        <option>Choose a number</option>
    </select>
    <input type="hidden" name="characterCardid" value=@characterCardId />
    <input type="button" onclick="submitVoteForm()" value="Vote">
</form>


<form id="frm1" action=@actionUp>
    <input id="hideit1" type="text" class="rating rating10" />
      
    <select id="selectNumber">
        <option>Choose a number</option>
    </select>

    <input type="button" onclick="myFunction1()" value="Upvote">
</form>
<form id="frm2" action=@actionDown>
    <input id="hideit2" type="text" class="rating rating10" />
    <input type="button" onclick="myFunction2()" value="Downvote">
</form>
-->
     
<!--<td>@Html.ActionLink("Vote", "Vote", new { characterCardid = Model.Id, rating = 1 })</td>
    -->
@{var sum = Model.Votes.Select(v => v.Value).Sum(); }



<!--@Html.DisplayText(sum.ToString())-->



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script>

    var select = document.getElementById("selectNumber");
    var options = ["1", "2", "3", "4", "5"];
    for (var i = 0; i < options.length; i++) {
        var opt = options[i];
        var el = document.createElement("option");
        el.textContent = opt;
        el.value = opt;
        select.appendChild(el);
    }

    function submitVoteForm() {
        document.getElementById("voteForm").submit();
    }


   // document.getElementById("hideit1").style.display = 'none';
   // document.getElementById("hideit2").style.display = 'none';
    function myFunction1() {
        document.getElementById("frm1").submit();

    }
    function myFunction2() {
        document.getElementById("frm2").submit();

    }

$(function ()
{
    $('.rating').rating();
});

function save(){



}

</script>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}





RPG_Buddy/RPG_Buddy/Views/CharacterCard/Index.cshtml
@model IEnumerable<RPG_Buddy.Models.CharacterCard>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Id)</td>
                <!--<td>@Html.ActionLink("Details", "Details", new { id = item.Id })</td>-->
                <td>@Html.ActionLink("Edit", "Edit", new { id= item.Id})</td>
                <td>@Html.ActionLink("Delete", "Delete", new { id = item.Id })</td>
                
            </tr>
        }
    </tbody>
</table>


RPG_Buddy/RPG_Buddy/Views/CharacterCard/Upvote.cshtml


<h2>Dodano plusa</h2>



<table class="table table-bordered table-striped">

    
</table>

RPG_Buddy/RPG_Buddy/Views/CharacterCard/Vote.cshtml
@model RPG_Buddy.Models.CharacterVote

@{
    ViewBag.Title = "Vote";

}

@{ int rating = ViewBag.rating;

    if (rating == null) { rating = 0; }

    string status = ViewBag.querystatus;}

<h2>Vote</h2>

<h2>Dodano ocenę: @rating</h2>





RPG_Buddy/RPG_Buddy/Views/CharacterCard/VotedAlready.cshtml


<h2>Już oddano taki głos</h2>



<table class="table table-bordered table-striped">

    
</table>