RPG_Buddy/RPG_Buddy/Models/ItemCard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RPG_Buddy.Models
{
    public class ItemCard
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual List<ItemCardFormValue> ItemCardFormValues { get; set; }

        public int Rating { get; set; }
        public List<ItemVote> Votes { get; set; }


    }
}

RPG_Buddy/RPG_Buddy/Models/ItemCardViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RPG_Buddy.Models
{
    public class ItemCardViewModel
    {
        public string ImieNazwisko { get; set; }
        public string ItemTemplate { get; set; }
        public List<string> ItemTemplateNames { get; set; }
    }
}

RPG_Buddy/RPG_Buddy/Controllers/ItemCardController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RPG_Buddy.Models;
using System.Diagnostics;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace RPG_Buddy.Controllers
{
    public class ItemCardController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ItemCard
        public ActionResult Index()
        {
            return View(db.ItemCards.ToList());
        }

        // GET: ItemCard/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemCard ItemCard = db.ItemCards.Find(id);
            if (ItemCard == null)
            {
                return HttpNotFound();
            }
            return View(ItemCard);
        }

        // GET: ItemCard/Create
        public ActionResult Create()
        {
            var model = new ItemCardViewModel();
            model.ItemTemplateNames = db.ItemTemplates.Select(x => x.Name).ToList();
            return View(model);
        }

        // POST: ItemCard/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Create(object obj)
        {
            var keys = Request.Form.AllKeys;

            var ItemCard = new ItemCard();
            ItemCard.Name = Request.Form[keys[0]];

            var formValues = new List<ItemCardFormValue>();

            for (int i = 1; i < keys.Length; i++)
            {
                formValues.Add(new ItemCardFormValue
                {
                    Name = keys[i],
                    Value = Request.Form[keys[i]]
                });
            }
            //walidacja
            for (int i = 1; i < (formValues.Count); i++)
            {

                int value;
                if (int.TryParse(formValues[i].Value, out value))
                {
                    //OK
                }
                else
                    formValues[i].Value = "0";

            }
            ItemCard.ItemCardFormValues = formValues;
            db.ItemCards.Add(ItemCard);
            db.SaveChanges();

            return RedirectToAction("Index");
        }
        [HttpPost]
        public JsonResult GetTemplate(string name)
        {
            var result = db.ItemTemplates.FirstOrDefault(x => x.Name == name);
            return Json(result);
        }

        // GET: ItemCard/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemCard ItemCard = db.ItemCards.Find(id);
            ItemCardViewModel vm = new ItemCardViewModel();
            if (ItemCard == null)
            {
                return HttpNotFound();
            }
            return View(ItemCard);
        }

        // POST: ItemCard/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.

        //public ActionResult Edit([Bind(Include = "Id,ImieNazwisko,Narodowosc,Rasa,Profesja,Archetyp,Krzepa,Zrecznosc,Przenikliwosc,Opanowanie,Charyzma,Umiejetnosci")] ItemCard ItemCard)

       /* public ActionResult Edit(ItemCard ItemCard)
        {
            var r = Request;
            var form = r.Form;
            var keys = Request.Form.AllKeys;
            var data = new List<string>();

            for (var i = 1; i < keys.Count(); i++) {
                data.Add(r[keys[i]]);
            }

            if (ModelState.IsValid)
            {
                db.Entry(ItemCard).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ItemCard);
        }*/

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(string Name, int Id, string[] formItem)
        {

            var r = Request;

            ItemCard itemCard = db.ItemCards.Find(Id);
            if (ModelState.IsValid)
            {
                itemCard.Name = Name;
                var fItem = Request["formItem.Value"];
                var items = fItem.Split(',');
                var values = items.Select(i => i).ToList();

                //db.Entry(characterCard).State = EntityState.Deleted; 
                //db.Entry(characterCard).State = EntityState.Modified;

                //characterCard.CharacterCardFormValues.Clear();

                //db.Entry(characterCard.CharacterCardFormValues).

                //db.SaveChanges();
                //characterCard.CharacterCardFormValues = values;
                //db.Entry(characterCard).State = EntityState.Modified;
                //TryUpdateModel(characterCard);
                //db.Entry(characterCard).State = EntityState.Modified;

                for (var i = 0; i < itemCard.ItemCardFormValues.Count; i++)
                {

                    itemCard.ItemCardFormValues[i].Value = values[i];

                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(itemCard);
        }


        // GET: ItemCard/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ItemCard ItemCard = db.ItemCards.Find(id);
            if (ItemCard == null)
            {
                return HttpNotFound();
            }
            return View(ItemCard);
        }

        // POST: ItemCard/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ItemCard ItemCard = db.ItemCards.Find(id);
            db.ItemCards.Remove(ItemCard);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // /ItemCard/Vote/?itemId=1&Rating=10
        public ActionResult Vote(int itemId, int rating=1) {

            //ItemCard ic = db.ItemCards.Find(itemId);

            //string userId = User.Identity.GetUserId();

            ApplicationUser user = System.Web.HttpContext.Current.GetOwinContext().GetUserManager<ApplicationUserManager>().FindById(System.Web.HttpContext.Current.User.Identity.GetUserId());
            string userId = user.Id;

            if (userId != null)
            {

                ItemVote iv = new ItemVote(rating, itemId, userId);

                // var votes = from v in db.ItemVotes select  
                var votes = db.ItemVotes.Where(v => v.ItemCardId == itemId && v.UserId == userId);
                if (votes.Count() == 0)
                {
                    db.ItemVotes.Add(iv);
                    ItemCard item = db.ItemCards.Find(itemId);
                    item.Votes.Add(iv);
                    db.Entry(item).State = EntityState.Modified;
                    db.SaveChanges();

                    //TODO: make sure item has not been rated by this user before
                    ViewBag.rating = rating;
                    ViewBag.querystatus = "OK";
                    return View("Vote");
                }
               else {

                    if (votes.Count() == 1)
                    {
                        var oldVote = votes.First();
                        if (oldVote.Value == rating) { return View("VotedAlready"); }
                        oldVote.Value = rating;
                        db.Entry(oldVote).State = EntityState.Modified;
                        db.SaveChanges();
                        ViewBag.rating = rating;
                        ViewBag.querystatus = "OK";
                        return View("Vote");
                    }

                    /*   ViewBag.querystatus = "FAILURE";
                       return View("Vote");*/
                    return View("VotedAlready");
                }

            }
            ViewBag.querystatus = "FAILURE";
            return View("Vote");

        }

        public int getTotalRating(int Id)
        {

            var votes = db.ItemVotes.Where(v => v.ItemCardId == Id).ToList();
            if (votes.Count != 0)
            {
                var sum = votes.Sum(v => v.Value);
                return sum;
            }
            else return 0;
            
        }

        /*public ActionResult Upvote()
        {


            
            int votePower = 1;

            

            List<int> upvotedList;
            int idFromSession = (int)Session["id"];



            if (Session["downvoted"] != null)
            {
                List<int> dList = (List<int>)Session["downvoted"];
                if (dList.Contains(idFromSession))
                {
                    votePower = 2;
                }
            }


            if (Session["upvoted"] != null)
            {
                upvotedList = (List<int>)Session["upvoted"];
                if (upvotedList.Contains(idFromSession))
                {

RPG_Buddy/RPG_Buddy/Views/ItemCard/Create.cshtml
@model RPG_Buddy.Models.ItemCardViewModel

@{
    ViewBag.Title = "Create";
}


<form id="nameForm">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ItemCard</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.DropDownListFor(m => m.ItemTemplate, new SelectList(Model.ItemTemplateNames), new { @class = "form-control", id = "dropDown" })
        </div>


        <div class="form-group">
            <button type="button" id="formButton" value="Create" class="btn btn-default">Wybierz</button>
        </div>
    </div>
</form>

<h2>Create</h2>
<script type="text/javascript">
    $(document).ready(function () {

        var template;

        $("#dropDown").change(function () {
            //alert("Handler for .change() called.");
        });

        $("#formButton").click(function () {
            var selectedOption = $("#dropDown option:selected").text();
            console.log(selectedOption);
            $.ajax({
                method: 'post',
                url: "/ItemCard/GetTemplate",
                data: { name: selectedOption }
            }).done(function (data) {
                createForm(data, selectedOption);

            });

        });

        function createForm(data, selectedOption) {
            console.log("Selected option aklfjsalkdjsakl", selectedOption);
            $("#nameForm").hide();
            // Generate a form
            //var template1 = { "attributes": ["atr1", "atr2"], "constraints": [{ "maxVal": "10" }, { "minVal": "0" }] }
            //var template = { "attributes": ["sila", "sila", "moc"], "constraints": [{ "maxVal": "100" }, { "minVal": "0" }, { "pointsTotal": "50" }, { "maxVal": "5" }, { "minVal": "50" }, { "pointsTotal": "80" }] }
            console.log(data.Schema, null, 2);
            var template = JSON.parse(data.Schema);
            console.log(JSON.stringify(template, null, 2));
            var html = [];

            firstName = {
                "name": "username",
                "caption": "Nazwa postaci",
                "type": "text",
                "class": "form-control"
            }
            html.push(firstName);

            for (var j = 0; j < template.attributes.length; j++) {
                var field = {};
                field.name = template.attributes[j];
                field.caption = template.attributes[j];
                field.type = "text";
                field.class = "form-control";
                html.push(field);
            }
            var submit = {
                "type": "submit",
                "value": "Create",
                "class": "btn btn-default"
            }
            html.push(submit);

            var input = $("<input>")
                .attr("type", "hidden")
                .attr("name", "name").val(selectedOption);
            $('#myform').append($(input));

            console.log(JSON.stringify(html, null, 2));

            $("#myform").dform({
                "action": "/ItemCard/Create",
                "method": "post",
                "html": html
            })

        }
        $(function () {
            // Generate a form
            //var template1 = { "attributes": ["atr1", "atr2"], "constraints": [{ "maxVal": "10" }, { "minVal": "0" }] }
            /*var template = { "attributes": ["sila", "sila", "moc"], "constraints": [{ "maxVal": "100" }, { "minVal": "0" }, { "pointsTotal": "50" }, { "maxVal": "5" }, { "minVal": "50" }, { "pointsTotal": "80" }] }
            console.log(JSON.stringify(template, null, 2));
            var html = [];

            firstName = {
                "name": "username",
                "id": "txt-username",
                "caption": "Username",
                "type": "text",
                "placeholder": "E.g. user@example.com"
            }

            for (var j = 0; j < template.attributes.length; j++) {
                var field = {};
                field.name = template.attributes[j];
                field.caption = template.attributes[j];
                field.type = "text";
                field.class = "form-control"
                //field.max = template.constraints[j].maxVal;
                html.push(field);
            }
            var submit = {
                "type": "submit",
                "value": "Create",
                "class": "btn btn-default"
            }
            html.push(submit);


            console.log(JSON.stringify(html, null, 2));



            $("#myform").dform({
                "action": "/ItemCard/Create",
                "method": "post",
                "html": html

            })*/
        });
    });

</script>
<div class="form-horizontal">
    <form id="myform"></form>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RPG_Buddy/RPG_Buddy/Views/ItemCard/Delete.cshtml
@model RPG_Buddy.Models.ItemCard

@{
    //Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>ItemCard</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

RPG_Buddy/RPG_Buddy/Views/ItemCard/Details.cshtml
@model RPG_Buddy.Models.ItemCard

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>ItemCard</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

RPG_Buddy/RPG_Buddy/Views/ItemCard/Downvote.cshtml


<h2>Dodano minusa</h2>





RPG_Buddy/RPG_Buddy/Views/ItemCard/Edit.cshtml
@model RPG_Buddy.Models.ItemCard

@{
    ViewBag.Title = "Edit";
}

<h2>Info</h2>


@using (Html.BeginForm("Edit", "ItemCard", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ItemCard</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        @foreach (var formItem in Model.ItemCardFormValues)
        {
            <div class="form-group">
                @Html.LabelFor(x => formItem.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(x => formItem.Value, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        }
        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
            
    </div>
}
@using (Html.BeginForm("Vote", "ItemCard", FormMethod.Post))
{
    @Html.Hidden("itemId", Model.Id);
   
    @Html.DropDownList("rating", new SelectList(new[] { 1, 2, 3, 4, 5 }))
    

    <input type="submit" value="Vote" />
}
@{Html.RenderAction("getTotalRating", new { Id = Model.Id });}





    <td>@Html.ActionLink("Vote", "Vote",  new { itemid = Model.Id, rating = 1 })</td>


<div>
    
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RPG_Buddy/RPG_Buddy/Views/ItemCard/Index.cshtml
@model IEnumerable<RPG_Buddy.Models.ItemCard>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.Id)</td>
                <td>@Html.ActionLink("Edit", "Edit", new { id = item.Id })</td>
                <td>@Html.ActionLink("Delete", "Delete", new { id = item.Id })</td>
            </tr>
        }
    </tbody>
</table>

RPG_Buddy/RPG_Buddy/Views/ItemCard/Upvote.cshtml


<h2>Dodano plusa</h2>





RPG_Buddy/RPG_Buddy/Views/ItemCard/Vote.cshtml
@model RPG_Buddy.Models.ItemVote

@{
    ViewBag.Title = "Vote";

}

@{ int rating = ViewBag.rating;

    if (rating == null) { rating = 0; }

    string status = ViewBag.querystatus;}

<h2>Vote</h2>

<h2>Dodano ocenę: @rating</h2>





RPG_Buddy/RPG_Buddy/Views/ItemCard/VotedAlready.cshtml


<h2>Już oddano taki głos</h2>



